[node]
detect-drivers = false

[relay]
url = "http://<public_ip_address>:4723/wd/hub"
status-endpoint = "/status"

configs = [
"1",'{"browserName":"chrome", "platformName": "Android", "platformVersion":"<version>", "deviceName": "<name>", "udid":"<udid>"}',
"1",'{"browserName":"chrome", "platformName": "iOS", "platformVersion":"<version>", "deviceName": "<name>","udid":"<udid>"}'
]

